/** Board-space geometry: right-handed XY, +X right, +Y up; positions and widths in mm. */
export interface Point {
  x: number
  y: number
}
export interface Terminal extends Point {
  layer: string
  pcb_port_id?: string
  pointId?: string
  layers?: string[]
}
export interface Connection {
  name: string
  source_trace_id?: string
  pointsToConnect: Terminal[]
  nominalTraceWidth?: number
  width?: number
}
export interface Bus {
  busId: string
  name?: string
  connectionNames: string[]
  maxLengthSkew?: number
  traceWidth?: number
  preferredLayer?: string
  preferredLayers?: string[]
  allowedLayers?: string[]
}
export interface Wire extends Point {
  route_type: "wire"
  layer: string
  width: number
}
export interface Via extends Point {
  route_type: "via"
  from_layer: string
  to_layer: string
  layers?: string[]
  via_diameter?: number
  via_hole_diameter?: number
}
export interface Trace {
  /** Ending vertex indices of chords generated by the smooth tuner. */
  curvedSegments?: number[]
  /** Inclusive handoff vertex indices; independently tune only outside this shared corridor. */
  coupledSection?: [number, number]
  type: "pcb_trace"
  pcb_trace_id: string
  connection_name?: string
  source_trace_id?: string
  route: (Wire | Via)[]
}
export interface Obstacle {
  type?: string
  componentId?: string
  shape?: "circle"
  ccwRotationDegrees?: number
  center: Point
  width: number
  height: number
  layers: string[]
  connectedTo: string[]
}
/** Structural SimpleRouteJson boundary; unknown routing primitives are rejected. */
export interface SimpleRouteJson {
  layerCount: number
  minTraceWidth: number
  minViaPadDiameter?: number
  minViaHoleDiameter?: number
  minViaHoleEdgeToViaHoleEdgeClearance?: number
  allowBlindAndBuriedVias?: boolean
  bounds: { minX: number; maxX: number; minY: number; maxY: number }
  connections: Connection[]
  obstacles: Obstacle[]
  traces?: Trace[]
  buses?: Bus[]
  defaultObstacleMargin?: number
  minTraceToPadEdgeClearance?: number
  minBoardEdgeClearance?: number
  outline?: Point[]
  differentialPairs?: Array<{
    connectionNames: [string, string]
    lengthTolerance: number
    traceGap?: number
    maxUncoupledLength?: number
  }>
}
export interface SolverOptions {
  /** Debugger-only abstract graph stage; ordinary routing does not capture it. */
  visualizeHypergraphTopology?: boolean
  /** Optional diagnostic observer. Receives detached snapshots only at stage
   * boundaries; intermediate geometry is not a validated routing solution. */
  onStage?: (snapshot: RoutingStageSnapshot) => void
  initialRouting?: "visibility" | "hypergraph"
  smoothTuning?: boolean
  denseSearch?: boolean
  maxLaneIterations?: number
  maxSearchIterations?: number
  /** Hypergraph topology retries per terminal assignment (default 4). */
  maxTopologyRetries?: number
}

export interface RoutingStageSnapshot {
  topology?: import("./route-hypergraph").RouteHypergraphTopology
  stage:
    | "local_dogbones"
    | "hypergraph_cover"
    | "route_cleanup"
    | "tuning_corridor"
    | "length_matching"
    | "validated_lanes"
    | "assembled_output"
  input: SimpleRouteJson
  traces: Trace[]
  stats: Record<string, unknown>
  attempt?: number
  routingStage?: "matched_buses" | "remaining_signals" | "all_signals"
}
